FROM node:20-alpine AS builder

WORKDIR /app
COPY package.json .
RUN npm install --omit=dev
COPY . .
RUN npm run build:prod

FROM node:20-alpine

WORKDIR /app
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json .
RUN npm install --omit=dev

CMD ["npm", "run", "start:prod"]