name: deploy-expiration

on:
  push:
    branches:
      - master
    paths:
      - 'expiration/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd expiration
          docker build -t cuongichtruong/ticketing-expiration .

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: docker push cuongichtruong/ticketing-expiration

      - name: Connect to DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Apply latest image
        run: |
          doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_ID }}
          kubectl rollout restart deployment expiration-depl -n ticketing
