name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Connect to DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Apply latest infra k8s manifests
        run: |
          doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_ID }}
          kubectl apply -f infra/k8s 
          kubectl apply -f infra/k8s-prod
