name: test auth

on:
  pull_request:
    paths:
      - 'auth/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd auth
          npm install

      - name: Run tests
        run: |
          cd auth
          npm run test:ci
